language: python
sudo: enabled
cache:
  directories:
  - $HOME/.cache/pip
  - /tmp/cached/
python:
- '3.5'
- '3.6'
- '3.7.2'
install:
- pip install -r requirements.txt
- pip install pytest==3.5.1
- pip install rasa_nlu --upgrade
- pip install rasa_core --upgrade
- pip install rasa_core_sdk --upgrade
script:
- python -m pytest tests