# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230527-183943-charcoal-skipper

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
# - name: LanguageModelFeaturizer
#   # Name of the language model to use
#   model_name: "gpt"
#   # Pre-Trained weights to be loaded
#   model_weights: "openai-gpt"
#   cache_dir: null
- name: "WhitespaceTokenizer"
  intent_tokenization_flag: True
  intent_split_symbol: "+"
- name: "CountVectorsFeaturizer"
- name: "DIETClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies: 
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    random_seed: 42
    epochs: 250
  - name: RulePolicy
