#!/usr/bin/env python3
"""Rescue the small product shots that live inside the printed menu.

Those crops are only 290-490 px wide in the source poster, so putting them on a
1080 px frame means a ~3x blow-up and the film shader was left doing that with
plain bilinear filtering - soft, mushy edges.

This script does the enlargement once, offline, where we can afford to be
careful about it:

  1. split into luma / chroma - JPEG throws most of its detail away in chroma,
     so smoothing chroma removes colour mottling without touching real detail
  2. enlarge 3x with Lanczos (a much better kernel than the GPU's bilinear)
  3. unsharp-mask the luma only, at a radius matched to the new pixel size, so
     edges come back without colour fringing
  4. a gentle local-contrast lift, which is what actually reads as "sharper"

The result is written to assets/photos/enhanced/ and used through
scene/photos.js like any other source photo.

    python3 scripts/enhance-crops.py
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
from PIL import Image, ImageFilter

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / 'assets' / 'photos' / 'enhanced'

# Regions worth rescuing: everything we show as a card, i.e. every crop that
# comes out of a printed menu rather than out of a real photograph.
TARGETS = ['nemSongTray', 'nemChienBowls', 'comboPhoto', 'miTronPhoto', 'miTronCheese',
           'fruitDam', 'fruitMix', 'fruitBox']

SCALE = 3


def local_contrast(luma: np.ndarray, radius: float = 22.0, strength: float = 0.35) -> np.ndarray:
    """Lift local contrast (a poor man's CLAHE) - what the eye reads as detail."""
    blurred = np.asarray(
        Image.fromarray(luma).filter(ImageFilter.GaussianBlur(radius)), dtype=np.float32
    )
    detail = luma.astype(np.float32) - blurred
    return np.clip(luma.astype(np.float32) + detail * strength, 0, 255).astype(np.uint8)


def enhance(img: Image.Image) -> Image.Image:
    y, cb, cr = img.convert('YCbCr').split()

    # chroma carries almost no real detail at this size - smooth the JPEG mottle
    cb = cb.filter(ImageFilter.GaussianBlur(1.1))
    cr = cr.filter(ImageFilter.GaussianBlur(1.1))

    w, h = img.size
    size = (w * SCALE, h * SCALE)
    y = y.resize(size, Image.LANCZOS)
    cb = cb.resize(size, Image.LANCZOS)
    cr = cr.resize(size, Image.LANCZOS)

    y = y.filter(ImageFilter.UnsharpMask(radius=SCALE * 0.9, percent=145, threshold=2))
    y = Image.fromarray(local_contrast(np.asarray(y)))

    out = Image.merge('YCbCr', (y, cb, cr)).convert('RGB')

    # a last very small high-frequency pass to crisp the edges after the merge
    return out.filter(ImageFilter.UnsharpMask(radius=1.4, percent=55, threshold=3))


def main() -> None:
    regions = json.loads((ROOT / 'scene' / 'regions.json').read_text())['regions']
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    manifest = {}
    cache: dict[str, Image.Image] = {}

    for name in TARGETS:
        r = regions[name]
        src = r['src'].replace('../', '')
        if src not in cache:
            cache[src] = Image.open(ROOT / src).convert('RGB')
        im = cache[src]
        w, h = im.size
        x0, y0, x1, y1 = r['rect']
        crop = im.crop((round(x0 * w), round(y0 * h), round(x1 * w), round(y1 * h)))
        big = enhance(crop)
        path = OUT_DIR / f'{name}.png'
        big.save(path)
        manifest[name] = {'file': f'enhanced/{name}.png', 'w': big.width, 'h': big.height}
        print(f'{name:15s} {crop.width}x{crop.height}  ->  {big.width}x{big.height}')

    (OUT_DIR / 'manifest.json').write_text(json.dumps(manifest, indent=2))

    # Generated module so the scene can use the rescues by name without anyone
    # having to keep a second copy of the pixel dimensions in sync by hand.
    lines = [
        '// GENERATED by scripts/enhance-crops.py - do not edit by hand.',
        '//',
        '// Upscaled rescues of the product shots that live inside the printed menu.',
        '// Each one is a whole file, so its region is simply the full frame.',
        '',
        'export const HD_PHOTOS = {',
    ]
    for name, m in manifest.items():
        lines.append(f"  hd_{name}: {{ src: '../assets/photos/{m['file']}', w: {m['w']}, h: {m['h']} }},")
    lines += ['};', '', 'export const HD_REGIONS = {']
    for name in manifest:
        lines.append(f"  {name}HD: {{ photo: 'hd_{name}', rect: [0, 0, 1, 1] }},")
    lines += ['};', '']
    (ROOT / 'scene' / 'photos-enhanced.js').write_text('\n'.join(lines))

    print(f'\nwrote {len(manifest)} files to {OUT_DIR}')
    print('wrote scene/photos-enhanced.js')


if __name__ == '__main__':
    main()
